 # Integration tests
_unit-tests: &unit-tests
  os: linux
  sudo: required
  language: minimal
  services: docker
  cache:
    directories:
      - deps
  install:
    - sudo sysctl -w vm.max_map_count=262144
  script:
    - docker-compose -f ./back/test.yml up


_app-deploy: &app-deploy
  stage: Deployments
  language: node_js
  node_js: 10
  cache:
    npm: true
    directories:
      - $HOME/.cache/pip
      - node_modules
  addons:
    apt:
      packages:
        - python
        - python-pip
  install:
    - pip install awscli --upgrade --user
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker-compose build
    - docker push yabbes/time-manager-back:latest
    - docker push yabbes/time-manager-front:latest

jobs:
  include:
    - <<: *unit-tests
      stage: Unit tests
      name: Unit Tests

    - <<: *app-deploy
      stage: Deployments
      name: Deployment