 # Integration tests
_integration-tests: &integration-tests
  os: linux
  sudo: required
  language: minimal
  services: docker
  cache:
    directories:
      - deps
  install:
    - sudo sysctl -w vm.max_map_count=262144
  script:
    - docker-compose -f ./back/test.yml up

jobs:
  include:
    # ---------------------------------------
    # Integration tests
    # ---------------------------------------
    - <<: *integration-tests
      stage: Integration tests
      name: Unit Tests