# Version of docker-compose
version: '3'

# Containers we are going to run
services:
    
  front:
    container_name: time-manager-front
    image: yabbes/time-manager-front
    ports:
      - "8080:8080"
    volumes:
      - "./pm2-dev.json:/app/front/pm2.json"
    command: npm run serve
    depends_on:
    # The db container needs to be started before we start this container
    - db
    - phoenix

  # Our Phoenix container
  phoenix:
    container_name: time-manager-back
    # The build parameters for this container.
    image: yabbes/time-manager-back
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: gotham_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: